# Generated by Django 2.1.2 on 2018-11-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='./media/imagenes/')),
                ('nombreMascota', models.CharField(max_length=30)),
                ('razaMascota', models.CharField(max_length=50)),
                ('descripcionMascota', models.TextField(blank=True, null=True)),
                ('estadoMascota', models.CharField(default='rescatado', max_length=50)),
            ],
        ),
    ]
